function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function formTpl(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"components\\form\\form.tmpl.pug":"div.form\r\n\tdiv.form__pad\r\n\t\tdiv.form__ctrl\r\n\t\t\tspan.form__open(data-action=\"add\") Add\r\n\t\t\tbutton.form__submit.form__hidden(form=\"add_form\" type=\"submit\")\r\n\t\t\t\tspan Append an item\r\n\t\t\tspan.form__close.form__hidden(data-action=\"close\") Cancel\r\n\t\t\tform#add_form.add__form.form__hidden\r\n\t\t\t\tdiv.form__elem.elem__inline\r\n\t\t\t\t\tlabel(for=\"url\") URL\r\n\t\t\t\t\tbr\r\n\t\t\t\t\tinput(type=\"text\" name=\"url\" required autofocus placeholder=\"Your URL\" tabindex=\"1\")\r\n\t\t\t\tdiv.form__elem.elem__inline\r\n\t\t\t\t\tlabel(for=\"anchor\") Anchor\r\n\t\t\t\t\tbr\r\n\t\t\t\t\tinput(type=\"text\" name=\"anchor\" required placeholder=\"Appropriate anchor\" tabindex=\"2\")\r\n\t\t\t\tbr(clear=\"all\")\r\n\t\t\t\tdiv.form__elem\r\n\t\t\t\t\tlabel(for=\"description\") Description\r\n\t\t\t\t\tbr\r\n\t\t\t\t\ttextarea(name=\"description\" rows=\"1\" tabindex=\"3\")\r\n"};
;pug_debug_line = 1;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cdiv class=\"form\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cdiv class=\"form__pad\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cdiv class=\"form__ctrl\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cspan class=\"form__open\" data-action=\"add\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "Add\u003C\u002Fspan\u003E";
;pug_debug_line = 5;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cbutton class=\"form__submit form__hidden\" form=\"add_form\" type=\"submit\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 6;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "Append an item\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E";
;pug_debug_line = 7;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cspan class=\"form__close form__hidden\" data-action=\"close\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "Cancel\u003C\u002Fspan\u003E";
;pug_debug_line = 8;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cform class=\"add__form form__hidden\" id=\"add_form\"\u003E";
;pug_debug_line = 9;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cdiv class=\"form__elem elem__inline\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Clabel for=\"url\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "URL\u003C\u002Flabel\u003E";
;pug_debug_line = 11;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cbr\u002F\u003E";
;pug_debug_line = 12;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cinput type=\"text\" name=\"url\" required=\"required\" autofocus=\"autofocus\" placeholder=\"Your URL\" tabindex=\"1\"\u002F\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 13;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cdiv class=\"form__elem elem__inline\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Clabel for=\"anchor\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "Anchor\u003C\u002Flabel\u003E";
;pug_debug_line = 15;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cbr\u002F\u003E";
;pug_debug_line = 16;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cinput type=\"text\" name=\"anchor\" required=\"required\" placeholder=\"Appropriate anchor\" tabindex=\"2\"\u002F\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 17;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cbr clear=\"all\"\u002F\u003E";
;pug_debug_line = 18;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cdiv class=\"form__elem\"\u003E";
;pug_debug_line = 19;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Clabel for=\"description\"\u003E";
;pug_debug_line = 19;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "Description\u003C\u002Flabel\u003E";
;pug_debug_line = 20;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Cbr\u002F\u003E";
;pug_debug_line = 21;pug_debug_filename = "components\\form\\form.tmpl.pug";
pug_html = pug_html + "\u003Ctextarea name=\"description\" rows=\"1\" tabindex=\"3\"\u003E\u003C\u002Ftextarea\u003E\u003C\u002Fdiv\u003E\u003C\u002Fform\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}